In [64]:
#<=========== Data Preprocessing ===========>
# Importing the libraries
import numpy as np           	  #For working with arrays 
import matplotlib.pyplot as plt   #For plotting graphs
import pandas as pd        	  #For working withs datasets in datafram formate

# Importing the dataset 
dataset = pd.read_csv('Sonar_Data.csv')     #Importing the data.csv file
X = dataset.iloc[:, :-1].values       # Independent veriables all rows and all columns expect last cloumn is in X
Y = dataset.iloc[:, -1].values        # Dependent veriable only last column and all rows

# Taking care of missing data
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, :-1])
X[:, :-1] = imputer.transform(X[:, :-1])
#print(X)

# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split   # Import skleran library
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.25, random_state = 0) # Create Test and Train set that will be 20% Test and 80% training with random selection enable

# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

Importing All The Classification Models

In [65]:
#Logistic Model-1
from sklearn.linear_model import LogisticRegression
classifier_1 = LogisticRegression()
classifier_1.fit(X_train, Y_train)

Y_pred_1 = classifier.predict(X_test)

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test, Y_pred_1)
print(cm)
acc_1 = accuracy_score(Y_test, Y_pred_1)

[[25  2]
 [12 13]]


In [66]:
#Navive Bayes-2
from sklearn.naive_bayes import GaussianNB
classifier_2 = GaussianNB()
classifier_2.fit(X_train, Y_train)

Y_pred_2 = classifier.predict(X_test)

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test, Y_pred_2)
print(cm)
acc_2 = accuracy_score(Y_test, Y_pred_2)

[[25  2]
 [12 13]]


In [67]:
#Support Vector Machine-3
from sklearn.svm import SVC
classifier_3 = SVC(kernel = 'linear')
classifier_3.fit(X_train, Y_train)

Y_pred_3 = classifier.predict(X_test)

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test, Y_pred_3)
print(cm)
acc_3 = accuracy_score(Y_test, Y_pred_3)

[[25  2]
 [12 13]]


In [68]:
#Kernal SVM-4
from sklearn.svm import SVC
classifier_4 = SVC(kernel = 'rbf')
classifier_4.fit(X_train, Y_train)

Y_pred_4 = classifier.predict(X_test)

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test, Y_pred_4)
print(cm)
acc_4 = accuracy_score(Y_test, Y_pred_4)

[[25  2]
 [12 13]]


In [69]:
#K Nearest Neighbour-5
from sklearn.neighbors import KNeighborsClassifier
classifier_5 = KNeighborsClassifier(n_neighbors = 5, metric='minkowski', p=2)
classifier_5.fit(X_train, Y_train)

Y_pred_5 = classifier.predict(X_test)

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test, Y_pred_5)
print(cm)
acc_5 = accuracy_score(Y_test, Y_pred_5)

[[25  2]
 [12 13]]


In [70]:
#Decision Tree-6
from sklearn.tree import DecisionTreeClassifier
classifier_6 = DecisionTreeClassifier()
classifier_6.fit(X_train, Y_train)

Y_pred_6 = classifier.predict(X_test)

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test, Y_pred_6)
print(cm)
acc_6 = accuracy_score(Y_test, Y_pred_6)

[[25  2]
 [12 13]]


In [71]:
#Random Forest-7
from sklearn.ensemble import RandomForestClassifier
classifier_7 = RandomForestClassifier(n_estimators= 10, criterion = 'entropy', random_state= 0)
classifier_7.fit(X_train, Y_train)

Y_pred_7 = classifier.predict(X_test)

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test, Y_pred_7)
print(cm)
acc_7 = (accuracy_score(Y_test, Y_pred_7))

[[25  2]
 [12 13]]


In [72]:
print(f'Accuracy Of Logistic Model = {acc_1*100}');
print(f'Accuracy Of Navive Bayes Model = {acc_2*100}');
print(f'Accuracy Of Support Vector Machine Model = {acc_3*100}');
print(f'Accuracy Of Kernal SVM Model = {acc_4*100}');
print(f'Accuracy Of K Nearest Neighbour Model = {acc_5*100}');
print(f'Accuracy Of Decision Tree Model = {acc_6*100}');
print(f'Accuracy Of Random Forest Model = {acc_7*100}');


Accuracy Of Logistic Model = 73.07692307692307
Accuracy Of Navive Bayes Model = 73.07692307692307
Accuracy Of Support Vector Machine Model = 73.07692307692307
Accuracy Of Kernal SVM Model = 73.07692307692307
Accuracy Of K Nearest Neighbour Model = 73.07692307692307
Accuracy Of Decision Tree Model = 73.07692307692307
Accuracy Of Random Forest Model = 73.07692307692307


In [73]:
accuraies = [acc_1, acc_2, acc_3, acc_4, acc_5, acc_6, acc_7]
max_accuracy = max(accuraies)
print(f'The Highest Accuracy : {round(max_accuracy*100,2)}')


The Highest Accuracy : 73.08


In [81]:
max_index=np.argmax(accuraies)
print(f'The Best Possible Model Is At Index : {max_index}')

The Best Possible Model Is At Index : 0


In [82]:
if(max_index == 0):
    Best_Model = 'Logistic Regression'
elif(max_index == 1):
    Best_Model = 'Navie Bayes'
elif(max_index == 2):
    Best_Model = 'SVM'
elif(max_index == 3):
    Best_Model = 'Kernel SVM'
elif(max_index == 4):
    Best_Model = 'KNN'
elif(max_index == 5):
    Best_Model = 'Decission Tree'
elif(max_index == 6):
    Best_Model = 'Random Forest'
    
print(f'The Best Model For This Dataset Is : {Best_Model}');

The Best Model For This Dataset Is : Logistic Regression
